name: Deploy application Flow

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string

jobs:
    deploy-pipeline:
        name: Deploy to ${{inputs.environment}}
        runs-on: ubuntu-latest
        environment: ${{inputs.environment}}

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
